### PR TITLE
Update Get-MMSSessionContent.ps1

### PR DESCRIPTION
**Pull request by SqlBenjamin**
Funny, I was looking at doing something like this last week and saw your twitter post about it so took a look. The proposed changes just simplify it a little and also allow to create a "Session Info.txt" file with some details about each session inside the folders - which I thought could be handy. I think it could be even better by removing the cabana type sessions...but didn't look to see if all conferences use the same format or not so figured having them wouldn't be that big of a deal for now. Whatcha think?

### CODE REVIEW

**Comment by SqlBenjamin** [comment]
Oh, I should have added this too...just found that one file returns a 404 and so there should be a try/catch for better handling. The following should replace lines 206 & 207 for the download/unblock action.

try
{
  Invoke-WebRequest -Uri $_.href -OutFile $outputfilepath -WebSession $mms;
  Unblock-File $outputFilePath;
}
catch
{
  Write-Output ".................$($PSItem.Exception) for '$($_.href)'...moving to next file...";
}

**Review by AndrewJNet — COMMENTED** [review]
This is awesome. You did a great job cleaning this up. I do appreciate the addition of the session details and like the idea of it being the default.  

What do you think of ConferenceId being a string array? Is it easier to to just pass an array to a foreach with the script inside if someone wants multiple years?

**Comment by SqlBenjamin** [comment]
Yeah, I thought about that too...but didn't want to go too crazy with the changes :) The question with that is, do we let them pass in the list/array of events or do we want them to choose from the specific values? The easiest would be to accept the list/array and then validate each of them against known values I guess...

**Comment by SqlBenjamin** [comment]
I made some more changes based on the comments, created a new PR so will close this one (if it lets me).

**Pull request closed without merging**
