### PR TITLE
Update Get-MMSSessionContent.ps1

### PR DESCRIPTION
**Pull request by SqlBenjamin**
Alright, made some changes as discussed in the other PR comments...

### CODE REVIEW

**Comment by SqlBenjamin** [comment]
cool; I was able to close the other PR. This should do what was discussed in the comments of the other PR. Take a look and let me know what you think.

**Comment by AndrewJNet** [comment]
Downloaded and tested single years, multiple years, multiple years with login and no login. Looking great. I'm ready to merge if you don't have anything else @SqlBenjamin

**Comment by SqlBenjamin** [comment]
I'm good! Thanks! Fun to help out!

**Comment by AndrewJNet** [comment]
Fun to collab on this! It's been a big community effort over the years. Appreciate your time and work!

**Pull request merged**
